name: sample-node-grpc-edge
services:
- name: edge
  environment_slug: node-js
  run_command: "npm run start-edge"
  github:
    repo: bojand/sample-node-grpc
    branch: main
  envs:
  - key: TARGET_COMPONENT
    value: "grpcsvc:5500"
    scope: RUN_TIME
- name: grpcsvc
  environment_slug: node-js
  run_command: "npm run start-svc"
  github:
    repo: bojand/sample-node-grpc
    branch: main
  internal_ports:
  - 5500