name: sample-node-grpc-edge
services:
- name: edge
  environment_slug: node-js
  run_command: "node index.js"
  github:
    repo: bojand/sample-node-grpc
    branch: edge
  envs:
  - key: TARGET_COMPONENT
    value: "grpcsvc:5500"
    scope: RUN_TIME
- name: grpcsvc
  environment_slug: node-js
  run_command: "node grpc_server.js"
  github:
    repo: bojand/sample-node-grpc
    branch: edge
  internal_ports:
  - 5500